nl-test: # Test with NLTemplate
	g++ --std c++14 src/NL-test.cpp src/NLTemplate/NLTemplate.cpp  -o ttml-test


lite-test: # test with Jinja2CppLight
	g++ --std c++14 src/lite-test.cpp src/Jinja2CppLight/Jinja2CppLight.cpp src/Jinja2CppLight/stringhelper.cpp -o ttml-test

